#!/bin/bash
RUNMODE=$(cat /home/ec2-user/runmode)
SERVER_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
cd /home/ec2-user/serverpod/active/oneshot_server
./bin/server --mode $RUNMODE --server-id $SERVER_ID --apply-migrations > /home/ec2-user/serverpod.log 2> /home/ec2-user/serverpod.err
