development:
  database: "ILpRp4L7sJi7dIhixYIYL2kafVyEdAxp"
  redis: "lgL9OOl8Zy-PYKlGC8rq7RNTOVH_7fdh"
  asaasAccessToken: ""

staging:
  database: "ILpRp4L7sJi7dIhixYIYL2kafVyEdAxp"
  redis: "lgL9OOl8Zy-PYKlGC8rq7RNTOVH_7fdh"
  asaasAccessToken: ""

production:
  database: "ILpRp4L7sJi7dIhixYIYL2kafVyEdAxp"
  redis: "lgL9OOl8Zy-PYKlGC8rq7RNTOVH_7fdh"
  asaasAccessToken: ""
