development:
  database: "ILpRp4L7sJi7dIhixYIYL2kafVyEdAxp"
  redis: "lgL9OOl8Zy-PYKlGC8rq7RNTOVH_7fdh"
  asaasAccessToken: "sua_chave_sandbox_aqui"

staging:
  database: "ILpRp4L7sJi7dIhixYIYL2kafVyEdAxp"
  redis: "lgL9OOl8Zy-PYKlGC8rq7RNTOVH_7fdh"
  asaasAccessToken: "sua_chave_sandbox_aqui"

production:
  database: "ILpRp4L7sJi7dIhixYIYL2kafVyEdAxp"
  redis: "lgL9OOl8Zy-PYKlGC8rq7RNTOVH_7fdh"
  asaasAccessToken: "sua_chave_producao_aqui"
